### ISSUE TITLE
find() working not correctly

### ISSUE THREAD

**Issue by jmas** [js-data/js-data-mongodb#9]
Hello.
I found that I can't use in `find()` with `id` of type `ObjectID` (`find()` can accept only `integer` or `string`). But in other case if I pass `string` like `553faa667f09fe5822e595c4` - adapter can't find record and throw error.
So we need to wrap `id` with `ObjectID` inside `find()`.
It seems this is an issue.

**Comment by jmdobry** [comment]
I do not use Mongo or have much experience with it. Any help from you or anyone else to make js-data-mongodb better support ObjectIDs would be much appreciated.

**Comment by jmas** [comment]
Thank you for quick response.
I will do some fix for this with tests ASAP.

**Comment by johngrogg** [comment]
@jmas did you ever get a fix working for this? If not I will try to get the project building locally and work out a solution for this.

Basic solution should be to include mongodb's bson ObjectId module, then in the find method, if `resourceConfig.idAttribute` is `_id` then check if the id passed in is a valid ObjectId hex string, if so use [ObjectID.createFromHexString](https://mongodb.github.io/node-mongodb-native/api-bson-generated/objectid.html#objectid-createfromhexstring) to create an ObjectId instance and override the original id value before assigning it into the params.

It'll be important to test if the id parameter is actually a valid ObjectId hexstring becuase it is possible to override the default behavior so that the _id value is a number or a string.

**Comment by jmdobry** [comment]
Thanks, I'm found a few other issues that I'm fixing right now. I'll cut a release in a bit.
